## Importing Dataset
player_db20 <- read.csv("D:/Amity/Capstone Project/Datasets/players_20.csv", stringsAsFactors = F)

## Removing unnecessary features from the dataset
player_db20 <- dplyr::select(player_db20, -c(long_name, dob, Height, Weight, Prefered.Position, Preferred.Foot,
                                             Weak.Foot, Skill.Moves, Work.Rate, Body.Type, Real.Face, Release.Clause, 
                                             player_tags, Jersey.Number, Loaned.From, Joined, Contract.Valid.Until, 
                                             nation_position, nation_jersey_number, pace, shooting, passing, dribbling, 
                                             defending, physic, gk_diving, gk_handling, gk_kicking, gk_reflexes, 
                                             gk_speed, gk_positioning, player_traits, ls, st, rs, lw, lf, cf, rf, rw, 
                                             lam, cam, ram, lm, lcm, cm, rcm, rm, lwb, ldm, cdm, rdm, rwb, lb, lcb, cb, 
                                             rcb, rb))

## Dealing with NAs
player_db20[is.na(player_db20)] <- 0

player_db20$Wage <- as.numeric(player_db20$Wage)
player_db20$Value <- as.numeric(player_db20$Value)
player_db20$Potential <- as.numeric(player_db20$Potential)
player_db20$Overall <- as.numeric(player_db20$Overall)
player_db20$Age <- as.numeric(player_db20$Age)
player_db20$ID <- as.numeric(player_db20$ID)
player_db20$Crossing <- as.numeric(player_db20$Crossing)
player_db20$Finishing <- as.numeric(player_db20$Finishing)
player_db20$HeadingAccuracy <- as.numeric(player_db20$HeadingAccuracy)
player_db20$ShortPassing <- as.numeric(player_db20$ShortPassing)
player_db20$Volleys <- as.numeric(player_db20$Volleys)
player_db20$Dribbling <- as.numeric(player_db20$Dribbling)
player_db20$Curve <- as.numeric(player_db20$Curve)
player_db20$FKAccuracy <- as.numeric(player_db20$FKAccuracy)
player_db20$LongPassing <- as.numeric(player_db20$LongPassing)
player_db20$BallControl <- as.numeric(player_db20$BallControl)
player_db20$Acceleration <- as.numeric(player_db20$Acceleration)
player_db20$SprintSpeed <- as.numeric(player_db20$SprintSpeed)
player_db20$Agility <- as.numeric(player_db20$Agility)
player_db20$Reactions <- as.numeric(player_db20$Reactions)
player_db20$Balance <- as.numeric(player_db20$Balance)
player_db20$ShotPower <- as.numeric(player_db20$ShotPower)
player_db20$Jumping <- as.numeric(player_db20$Jumping)
player_db20$Stamina <- as.numeric(player_db20$Stamina)
player_db20$Strength <- as.numeric(player_db20$Strength)
player_db20$LongShots <- as.numeric(player_db20$LongShots)
player_db20$Aggression <- as.numeric(player_db20$Aggression)
player_db20$Interceptions <- as.numeric(player_db20$Interceptions)
player_db20$Positioning <- as.numeric(player_db20$Positioning)
player_db20$Vision <- as.numeric(player_db20$Vision)
player_db20$Penalties <- as.numeric(player_db20$Penalties)
player_db20$Composure <- as.numeric(player_db20$Composure)
player_db20$Marking <- as.numeric(player_db20$Marking)
player_db20$StandingTackle <- as.numeric(player_db20$StandingTackle)
player_db20$SlidingTackle <- as.numeric(player_db20$SlidingTackle)
player_db20$GKDiving <- as.numeric(player_db20$GKDiving)
player_db20$GKHandling <- as.numeric(player_db20$GKHandling)
player_db20$GKKicking <- as.numeric(player_db20$GKKicking)
player_db20$GKPositioning <- as.numeric(player_db20$GKPositioning)
player_db20$GKReflexes <- as.numeric(player_db20$GKReflexes)
player_db20$Position <- as.factor(player_db20$Position)
player_db20$International.Reputation <- as.numeric(player_db20$International.Reputation)

## Scaling data set for Neural Network Prediction
MinOvr <- min(player_db20$Overall)
MinAge <- min(player_db20$Age)              
MinPot <- min(player_db20$Potential)
MinCro <- min(player_db20$Crossing)
MinFin <- min(player_db20$Finishing) 
MinHAc <- min(player_db20$HeadingAccuracy)
MinSps <- min(player_db20$ShortPassing)
MinDri <- min(player_db20$Dribbling)
MinBCt <- min(player_db20$BallControl) 
MinAcc <- min(player_db20$Acceleration)
MinSSp <- min(player_db20$SprintSpeed)
MinRec <- min(player_db20$Reactions)
MinBal <- min(player_db20$Balance) 
MinSPw <- min(player_db20$ShotPower)
MinSta <- min(player_db20$Stamina)
MinStr <- min(player_db20$Strength)
MinFKA <- min(player_db20$FKAccuracy)
MinVis <- min(player_db20$Vision)
MinPen <- min(player_db20$Penalties)
MinCom <- min(player_db20$Composure)
MinMar <- min(player_db20$Marking)
MinSTk <- min(player_db20$StandingTackle) 
MinSlT <- min(player_db20$SlidingTackle)
MinGKD <- min(player_db20$GKDiving)
MinGKH <- min(player_db20$GKHandling)
MinGKK <- min(player_db20$GKKicking)
MinGKP <- min(player_db20$GKPositioning)
MinGKR <- min(player_db20$GKReflexes)
MinInt <- min(player_db20$International.Reputation)

MaxOvr <- max(player_db20$Overall)
MaxAge <- max(player_db20$Age)              
MaxPot <- max(player_db20$Potential)
MaxCro <- max(player_db20$Crossing)
MaxFin <- max(player_db20$Finishing) 
MaxHAc <- max(player_db20$HeadingAccuracy)
MaxSps <- max(player_db20$ShortPassing)
MaxDri <- max(player_db20$Dribbling)
MaxBCt <- max(player_db20$BallControl) 
MaxAcc <- max(player_db20$Acceleration)
MaxSSp <- max(player_db20$SprintSpeed)
MaxRec <- max(player_db20$Reactions)
MaxBal <- max(player_db20$Balance) 
MaxSPw <- max(player_db20$ShotPower)
MaxSta <- max(player_db20$Stamina)
MaxStr <- max(player_db20$Strength)
MaxFKA <- max(player_db20$FKAccuracy)
MaxVis <- max(player_db20$Vision)
MaxPen <- max(player_db20$Penalties)
MaxCom <- max(player_db20$Composure)
MaxMar <- max(player_db20$Marking)
MaxSTk <- max(player_db20$StandingTackle) 
MaxSlT <- max(player_db20$SlidingTackle)
MaxGKD <- max(player_db20$GKDiving)
MaxGKH <- max(player_db20$GKHandling)
MaxGKK <- max(player_db20$GKKicking)
MaxGKP <- max(player_db20$GKPositioning)
MaxGKR <- max(player_db20$GKReflexes)
MaxInt <- max(player_db20$International.Reputation)

Overall <- scale(player_db20$Overall, center = MinOvr, scale = MaxOvr - MinOvr)
Age <- scale(player_db20$Age, center = MinAge, scale = MaxAge - MinAge)
Potential <- scale(player_db20$Potential, center = MinPot, scale = MaxPot - MinPot)
Crossing <- scale(player_db20$Crossing, center = MinCro, scale = MaxCro - MinCro)
Finishing <- scale(player_db20$Finishing, center = MinFin, scale = MaxFin - MinFin)
HeadingAccuracy <- scale(player_db20$HeadingAccuracy, center = MinHAc, scale = MaxHAc - MinHAc)
ShortPassing <- scale(player_db20$ShortPassing, center = MinSps, scale = MaxSps - MinSps)
Dribbling <- scale(player_db20$Dribbling, center = MinDri, scale = MaxDri - MinDri)
BallControl <- scale(player_db20$BallControl, center = MinBCt, scale = MaxBCt - MinBCt)
Acceleration <- scale(player_db20$Acceleration, center = MinAcc, scale = MaxAcc - MinAcc)
SprintSpeed <- scale(player_db20$SprintSpeed, center = MinSSp, scale = MaxSSp - MinSSp)
Reaction <- scale(player_db20$Reactions, center = MinRec, scale = MaxRec - MinRec)
Balance <- scale(player_db20$Balance, center = MinBal, scale = MaxBal - MinBal)
ShotPower <- scale(player_db20$ShotPower, center = MinSPw, scale = MaxSPw - MinSPw)
Stamina <- scale(player_db20$Stamina, center = MinSta, scale = MaxSta - MinSta)
Strength <- scale(player_db20$Strength, center = MinStr, scale = MaxStr - MinStr)
FKAccuracy <- scale(player_db20$FKAccuracy, center = MinFKA, scale = MaxFKA - MinFKA)
Vision <- scale(player_db20$Vision, center = MinVis, scale = MaxVis - MinVis)
Penalties <- scale(player_db20$Penalties, center = MinPen, scale = MaxPen - MinPen)
Composure <- scale(player_db20$Composure, center = MinCom, scale = MaxCom - MinCom)
Marking <- scale(player_db20$Marking, center = MinMar, scale = MaxMar - MinMar)
StandingTackle <- scale(player_db20$StandingTackle, center = MinSTk, scale = MaxSTk - MinSTk)
SlidingTackle <- scale(player_db20$SlidingTackle, center = MinSlT, scale = MaxSlT - MinSlT)
GKDiving <- scale(player_db20$GKDiving, center = MinGKD, scale = MaxGKD - MinGKD)
GKHandling <- scale(player_db20$GKHandling, center = MinGKH, scale = MaxGKH - MinGKH)
GKKicking <- scale(player_db20$GKKicking, center = MinGKK, scale = MaxGKK - MinGKK)
GKPositioning <- scale(player_db20$GKPositioning, center = MinGKP, scale = MaxGKP - MinGKP)
GKReflexes <- scale(player_db20$GKReflexes, center = MinGKR, scale = MaxGKR - MinGKR)
International.Reputation <- scale(player_db20$International.Reputation, center = MinInt, scale = MaxInt - MinInt)

player_db20_nn <- data.frame(Overall, Age, Potential, Crossing, Finishing, HeadingAccuracy, ShortPassing,
                             Dribbling, BallControl, Acceleration, SprintSpeed, Reaction, Balance,  ShotPower,
                             Stamina, Strength, FKAccuracy, Vision, Penalties, Composure, Marking, StandingTackle, 
                             SlidingTackle, GKDiving, GKHandling, GKKicking, GKPositioning, GKReflexes, International.Reputation)

player_db20_nn_ <- data.frame(Overall, Age, Potential, International.Reputation)
