## Importing Dataset
player_db18 <- read.csv("D:/Amity/Capstone Project/Datasets/FIFA 18.csv", stringsAsFactors = F)

## Removing unnecessary features from the data set
player_db18 <- dplyr::select(player_db18, -c(Sr.Nos., Special, CAM, CB, CDM, CF, CM, LAM, LB, LCB, LCM, LDM, LF, LM,
                                              LS, LW, LWB, RAM, RB, RCB, RCM, RDM, RF, RM, RS, RW, RWB, ST))

## Dealing NAs
player_db18[is.na(player_db18)] <- 0

player_db18$Crossing <- strtrim(player_db18$Crossing, 2)
player_db18$Finishing <- strtrim(player_db18$Finishing, 2)
player_db18$HeadingAccuracy <- strtrim(player_db18$HeadingAccuracy, 2)
player_db18$ShortPassing <- strtrim(player_db18$ShortPassing, 2)
player_db18$Volleys <- strtrim(player_db18$Volleys, 2)
player_db18$Dribbling <- strtrim(player_db18$Dribbling, 2)
player_db18$Curve <- strtrim(player_db18$Curve, 2)
player_db18$FKAccuracy <- strtrim(player_db18$FKAccuracy, 2)
player_db18$LongPassing <- strtrim(player_db18$LongPassing, 2)
player_db18$BallControl <- strtrim(player_db18$BallControl, 2)
player_db18$Acceleration <- strtrim(player_db18$Acceleration, 2)
player_db18$SprintSpeed <- strtrim(player_db18$SprintSpeed, 2)
player_db18$Agility <- strtrim(player_db18$Agility, 2)
player_db18$Reactions <- strtrim(player_db18$Reactions, 2)
player_db18$Balance <- strtrim(player_db18$Balance, 2)
player_db18$ShotPower <- strtrim(player_db18$ShotPower, 2)
player_db18$Jumping <- strtrim(player_db18$Jumping, 2)
player_db18$Stamina <- strtrim(player_db18$Stamina, 2)
player_db18$Strength <- strtrim(player_db18$Strength, 2)
player_db18$LongShots <- strtrim(player_db18$LongShots, 2)
player_db18$Aggression <- strtrim(player_db18$Aggression, 2)
player_db18$Interceptions <- strtrim(player_db18$Interceptions, 2)
player_db18$Positioning <- strtrim(player_db18$Positioning, 2)
player_db18$Vision <- strtrim(player_db18$Vision, 2)
player_db18$Penalties <- strtrim(player_db18$Penalties, 2)
player_db18$Composure <- strtrim(player_db18$Composure, 2)
player_db18$Marking <- strtrim(player_db18$Marking, 2)
player_db18$StandingTackle <- strtrim(player_db18$StandingTackle, 2)
player_db18$SlidingTackle <- strtrim(player_db18$SlidingTackle, 2)
player_db18$GKDiving <- strtrim(player_db18$GKDiving, 2)
player_db18$GKHandling <- strtrim(player_db18$GKHandling, 2)
player_db18$GKKicking <- strtrim(player_db18$GKKicking, 2)
player_db18$GKPositioning <- strtrim(player_db18$GKPositioning, 2)
player_db18$GKReflexes <- strtrim(player_db18$GKReflexes, 2)

player_db18$Crossing <- as.numeric(player_db18$Crossing)
player_db18$Finishing <- as.numeric(player_db18$Finishing)
player_db18$HeadingAccuracy <- as.numeric(player_db18$HeadingAccuracy)
player_db18$ShortPassing <- as.numeric(player_db18$ShortPassing)
player_db18$Volleys <- as.numeric(player_db18$Volleys)
player_db18$Dribbling <- as.numeric(player_db18$Dribbling)
player_db18$Curve <- as.numeric(player_db18$Curve)
player_db18$FKAccuracy <- as.numeric(player_db18$FKAccuracy)
player_db18$LongPassing <- as.numeric(player_db18$LongPassing)
player_db18$BallControl <- as.numeric(player_db18$BallControl)
player_db18$Acceleration <- as.numeric(player_db18$Acceleration)
player_db18$SprintSpeed <- as.numeric(player_db18$SprintSpeed)
player_db18$Agility <- as.numeric(player_db18$Agility)
player_db18$Reactions <- as.numeric(player_db18$Reactions)
player_db18$Balance <- as.numeric(player_db18$Balance)
player_db18$ShotPower <- as.numeric(player_db18$ShotPower)
player_db18$Jumping <- as.numeric(player_db18$Jumping)
player_db18$Stamina <- as.numeric(player_db18$Stamina)
player_db18$Strength <- as.numeric(player_db18$Strength)
player_db18$LongShots <- as.numeric(player_db18$LongShots)
player_db18$Aggression <- as.numeric(player_db18$Aggression)
player_db18$Interceptions <- as.numeric(player_db18$Interceptions)
player_db18$Positioning <- as.numeric(player_db18$Positioning)
player_db18$Vision <- as.numeric(player_db18$Vision)
player_db18$Penalties <- as.numeric(player_db18$Penalties)
player_db18$Composure <- as.numeric(player_db18$Composure)
player_db18$Marking <- as.numeric(player_db18$Marking)
player_db18$StandingTackle <- as.numeric(player_db18$StandingTackle)
player_db18$SlidingTackle <- as.numeric(player_db18$SlidingTackle)
player_db18$GKDiving <- as.numeric(player_db18$GKDiving)
player_db18$GKHandling <- as.numeric(player_db18$GKHandling)
player_db18$GKKicking <- as.numeric(player_db18$GKKicking)
player_db18$GKPositioning <- as.numeric(player_db18$GKPositioning)
player_db18$GKReflexes <- as.numeric(player_db18$GKReflexes)
player_db18$International.Reputation <- as.numeric(player_db18$International.Reputation)
